// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserPublicKey struct {
	Modulus              string   `protobuf:"bytes,1,opt,name=modulus,proto3" json:"modulus,omitempty"`
	Exponent             int64    `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPublicKey) Reset()         { *m = UserPublicKey{} }
func (m *UserPublicKey) String() string { return proto.CompactTextString(m) }
func (*UserPublicKey) ProtoMessage()    {}
func (*UserPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *UserPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPublicKey.Unmarshal(m, b)
}
func (m *UserPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPublicKey.Marshal(b, m, deterministic)
}
func (m *UserPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPublicKey.Merge(m, src)
}
func (m *UserPublicKey) XXX_Size() int {
	return xxx_messageInfo_UserPublicKey.Size(m)
}
func (m *UserPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserPublicKey proto.InternalMessageInfo

func (m *UserPublicKey) GetModulus() string {
	if m != nil {
		return m.Modulus
	}
	return ""
}

func (m *UserPublicKey) GetExponent() int64 {
	if m != nil {
		return m.Exponent
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*UserToken)(nil), "user.UserToken")
	proto.RegisterType((*UserPublicKey)(nil), "user.UserPublicKey")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x5b, 0xfb, 0x1e, 0x50, 0xcb, 0x2a, 0x1a, 0x22, 0x48, 0xcd, 0x49, 0x3c, 0x6c, 0x40,
	0xff, 0x02, 0x85, 0x22, 0x45, 0x0f, 0x52, 0xf4, 0xa2, 0x07, 0x49, 0x9a, 0x69, 0x0c, 0x4d, 0x76,
	0x42, 0xb2, 0x8b, 0xad, 0x7f, 0xbd, 0xcc, 0xe6, 0x51, 0x7a, 0xca, 0xf7, 0xcb, 0x7c, 0xf3, 0xd8,
	0x0f, 0xa6, 0x79, 0x41, 0x9a, 0x7c, 0x53, 0x62, 0x21, 0xad, 0x14, 0x7d, 0xd6, 0xee, 0x55, 0x4c,
	0x14, 0xa7, 0xe8, 0xdb, 0x7f, 0xa1, 0x59, 0xfb, 0x98, 0xe5, 0x7a, 0x57, 0x59, 0xbc, 0x2f, 0x18,
	0x7f, 0x94, 0x58, 0x2c, 0xd4, 0x9a, 0xc4, 0x25, 0x8c, 0xb8, 0xe1, 0x3b, 0x89, 0x9c, 0xee, 0xac,
	0x7b, 0x3b, 0x59, 0x0e, 0x19, 0x17, 0x91, 0x70, 0x61, 0xcc, 0x4a, 0x05, 0x19, 0x3a, 0x47, 0xb6,
	0xd2, 0x32, 0xd7, 0xf2, 0xa0, 0x2c, 0x7f, 0xa9, 0x88, 0x9c, 0x5e, 0x55, 0x6b, 0xd8, 0xbb, 0x81,
	0x09, 0x0f, 0x7f, 0xa7, 0x0d, 0x2a, 0x71, 0x0e, 0x03, 0xcd, 0xa2, 0x9e, 0x5d, 0x81, 0x37, 0x87,
	0x63, 0xb6, 0xbc, 0x99, 0x30, 0x4d, 0x56, 0x2f, 0xb8, 0x13, 0x0e, 0x8c, 0x32, 0x8a, 0x4c, 0x6a,
	0xca, 0xda, 0xd8, 0x20, 0x6f, 0xc2, 0x6d, 0x4e, 0x0a, 0x95, 0xb6, 0x57, 0xf4, 0x96, 0x2d, 0xdf,
	0x1b, 0xe8, 0xf3, 0x18, 0x71, 0x07, 0x83, 0x57, 0x8a, 0x13, 0x25, 0x4e, 0xa4, 0xcd, 0xa1, 0x79,
	0x9b, 0x7b, 0xba, 0x67, 0x7b, 0x8e, 0xd7, 0x11, 0x8f, 0x30, 0x7d, 0x46, 0x7d, 0xb8, 0xfd, 0x42,
	0x56, 0x61, 0xc9, 0x26, 0x2c, 0x39, 0xe7, 0xb0, 0xdc, 0xb3, 0x7d, 0x7b, 0x6b, 0xf6, 0x3a, 0x4f,
	0xb3, 0xcf, 0xeb, 0x38, 0xd1, 0x3f, 0x26, 0x94, 0x2b, 0xca, 0xfc, 0x08, 0xff, 0x36, 0x14, 0x68,
	0x7f, 0xcb, 0xde, 0x3a, 0xee, 0xa1, 0xfd, 0x3c, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x66, 0xdf,
	0xc0, 0xdb, 0x9d, 0x01, 0x00, 0x00,
}
